using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Consts
{
    public static int GoldPerOnce = 8;
    public static int LumberPerOnce = 4;
    public static float LumberPerTreeGiveTime = 4;
    public static string Key_PVPRankTime = "prtt";
    public static string Key_DragonRankTime = "drtt";
    public static string Key_IOGameRankTime = "dftt";
    public static string Key_MineRankTime = "mntt";
    public static string Key_SacrificeRankTime = "ggtt";
    public static string Key_MaskRankTime = "mktt";
    public static string Key_DiceRankTime = "dctt";

    public static string Key_DarkForest = "darkforest";
    public static string Key_Dragon = "dragon";
    public static string Key_Arena = "arena";
    public static string Key_GodGift = "sacrifice";
    public static string Key_Mine = "mine";
    public static string Key_Mask = "mask";
    public static string Key_Dice = "dice";
    public static string Key_AutoDiceRank = "Key_AutoDiceIndex";
    public static string Key_AutoDiceStat = "Key_AutoDiceStat";
    public static int IOMaxLevel = 6;
    public static int IO_TIME_LIMIT = 304;
    public static int MaskAdSummonCount = 10;
    public static int SkillAdSummonCount = 10;
    public static int MaskAdPerDay = 3;
    public static int SkillAdPerDay = 3;
    // 이벤트 시간 키
    public const string Key_GodGiftEventTime = "gget";
    public const string Key_MineEventTime = "mnet";
    public const string Key_MaskEventTime = "mket";
    public const string Key_DiceEventTime = "dcet";
    public const string Key_DarkforestEventTime = "dfet";
    public const string Key_DragonEventTime = "drgt";
    public const string Key_ArenaEventTime = "aren";

    // 이벤트 보상 가능성 키
    // public const string Key_GodGiftRewardPending = "ggrp";
    // public const string Key_MineRewardPending = "mnrp";
    // public const string Key_MaskRewardPending = "mkrp";
    // public const string Key_DiceRewardPending = "dcrp";
    // public const string Key_DarkforestRewardPending = "dfrp";
    // public const string Key_DragonRewardPending = "drrp";
    // public const string Key_ArenaRewardPending = "arenp";
    /// <summary>
    /// 0: 미확인, 1: 확인 후 없음, 2: 확인 후 있음, 3: 받음
    /// </summary>
    public static string Key_PreviousRankRewardReceivedFormat = "PRRRcv_{0}";
    public static string Key_UUID = "Key_UUID";
    public static string Key_UserLevelFormat = "UserLevel{0}";
    public static string Key_NoticeIndex = "Key_NoticeIndex";
    public static string Key_Maint = "Key_Maint";
    public static string Key_NoticeStartTime = "Key_NoticeStartTime";
    public static string Key_NoticeEndTime = "Key_NoticeEndTime";
    public static string Key_NoticeContent = "Key_NoticeContent";
    public static string Key_NoticeTime = "Key_NoticeTime";
    public static string Key_MaintStartTime = "Key_MaintStartTime";
    public static string Key_MaintEndTime = "Key_MaintEndTime";
    public static string Key_MaintContent = "Key_MaintContent";
    public static string Key_LastLotteryEventID = "LastLotteryEventID";
    public static string Key_LastRouletteEventID = "LastRouletteEventID";
    public static string Key_RouletteEventRewardReceived = "RlttEvtRwdRcvd";
    public static string Key_LastSevenDaysEventID = "LastSevenEventID";
    // public static string Key_MIOPVPBestScore = "MIOPVPBest";
    public static string Key_MIOPVPBestScore_Top5 = "IOBstT5";
    public static string Key_MineLab = "MineLab";
    public static string Key_IdleDate = "IdleDate";
    public static string Key_DailyQuest = "DailyQuest";
    public static string Key_ChestLevelUp = "ChestLevelUp";
    public static string Key_MonthlyRedstonePack0 = "MonthlyRedstonePack0";
    public static string Key_MonthlyRedstonePack1 = "MonthlyRedstonePack1";
    public static string Key_WeekQuest = "WeeklyQuest";
    public static string Key_IOBestLevel = "IOBestLevel";
    public static string Key_MaskAdPerDay = "Key_MaskAdPerDay";
    public static string Key_SkillAdPerDay = "Key_SkillAdPerDay";
    public static string Key_MaskSummonRewardLevelReceived = "MskSRLv";
    public static string Key_SkillSummonRewardLevelReceived = "SklSRLv";
    public static string Key_SkillTicketBuyCount = "SkillTicketBuyCount";
    public static string Key_MaskTicketBuyCount = "MaskTicketBuyCount";
    public static string Key_EquipmentTicketUseCount = "EqpTktUseCnt";
    public static string IAP_GEM0 = "IAP_GEM0";
    public static string IAP_GEM1 = "IAP_GEM1";
    public static string IAP_GEM2 = "IAP_GEM2";
    public static string IAP_GEM3 = "IAP_GEM3";
    public static string IAP_GEM4 = "IAP_GEM4";
    public static string IAP_PACK_REMOVE_ADS = "pkg.adremove";
    public static string IAP_minePackageRecharge = "minePackageRecharge";
    public static string IAP_minePackageMaxTicket = "minePackageMaxTicket";
    public static string IAP_minePackageResearchPrice = "minePackageResearchPrice";
    public static string IAP_minePackageLv0 = "minePackageLv0";
    public static string IAP_minePackageLv1 = "minePackageLv1";
    public static string IAP_minePackageLv2 = "minePackageLv2";
    public static string IAP_minePackageLv3 = "minePackageLv3";
    public static string IAP_minePackageLv4 = "minePackageLv4";
    public static string IAP_HotDeal0 = "IAP_HotDeal0";
    public static string IAP_HotDeal1 = "IAP_HotDeal1";
    public static string IAP_HotDeal2 = "IAP_HotDeal2";
    public static string IAP_HotDeal3 = "IAP_HotDeal3";
    public static string IAP_HotDeal4 = "IAP_HotDeal4";
    // public static string IAP_PACK_DungeonVIP = "dungeon.vip";
    // public static string IAP_PACK_GemVIP = "gem.vip";
    // public static string IAP_PACK_MineVIP = "mine.vip";
    public static string IAP_PACK_SeasonPass = "pass.season";
    public static string IAP_PACK_LevelPass0 = "pass.level.1";
    public static string IAP_PACK_LevelPass1 = "pass.level.2";
    public static string IAP_PACK_LevelPass2 = "pass.level.3";
    public static string IAP_PACK_LevelPass3 = "pass.level.4";
    public static string IAP_PACK_BookPass = "pass.book";
    public static string IAP_PACK_MinePass0 = "pass.mine.1";
    public static string IAP_PACK_MinePass1 = "pass.mine.2";
    public static string IAP_PACK_MinePass2 = "pass.mine.3";
    public static string IAP_PACK_MinePass3 = "pass.mine.4";
    public static string IAP_PACK_StagePass0 = "pass.stage.1";
    public static string IAP_PACK_StagePass1 = "pass.stage.2";
    public static string IAP_PACK_StagePass2 = "pass.stage.3";
    public static string IAP_PACK_StagePass3 = "pass.stage.4";
    public static string IAP_PACK_MonthlyGem0 = "pkg.daily.rdst.lv1";
    public static string IAP_PACK_MonthlyGem1 = "pkg.daily.rdst.lv2";
    public static string IAP_PACK_StartLv0 = "pkg.starter.lv0";
    public static string IAP_PACK_StartLv1 = "pkg.starter.lv1";
    public static string IAP_PACK_StartLv2 = "pkg.starter.lv2";
    public static string IAP_PACK_StartLv3 = "pkg.starter.lv3";
    public static string IAP_PACK_DailyLv0 = "pkg.daily.lv0";
    public static string IAP_PACK_DailyLv1 = "pkg.daily.lv1";
    public static string IAP_PACK_DailyLv2 = "pkg.daily.lv2";
    public static string IAP_PACK_DailyLv3 = "pkg.daily.lv3";
    public static string IAP_PACK_7DaysEventPass = "pass.7days.event";
    public static string KEY_PostAdsCounter = "PstAdsCnt";
    public static string KEY_IdleRewardCounter = "IdlRwdCnt";
    public static string KEY_QuestAdsCounter = "QstAdsCnt";
    public static string KEY_SkillAdsCounter = "SklAdsCnt";
    public static string KEY_MaskAdsCounter = "MskAdsCnt";
    public static string KEY_ShopTKTNCounter = "Shop_cr_tktn_Cnt";
    public static string KEY_ShopCSTMCounter = "Shop_cr_cstm_Cnt";
    public static string KEY_ShopTimeTktCounter = "Shop_TimeTkt_Cnt";
    public static string KEY_ShopGodGiftTicketCounter = "Shop_GodGiftTkt_Cnt";
    public static string KEY_DailyQuestReceived = "DailyQuestReceivedCnt";
    public static string KEY_WeeklyQuestReceived = "WeeklyQuestReceivedCnt";
    public static string KEY_RepeatQuestReceived = "RepeatQuestReceivedCnt";
    // public static string KEY_AchievementQuestReceived = "AchievementQuestReceivedCnt";

    public static int GetIAPIndex(string id)
    {
        if (id.Equals(IAP_GEM0)) return 0;
        else if (id.Equals(IAP_GEM1)) return 1;
        else if (id.Equals(IAP_GEM2)) return 2;
        else if (id.Equals(IAP_GEM3)) return 3;
        else if (id.Equals(IAP_GEM4)) return 4;
        else if (id.Equals(IAP_PACK_REMOVE_ADS)) return 5;
        else if (id.Equals(IAP_minePackageRecharge)) return 6;
        else if (id.Equals(IAP_minePackageMaxTicket)) return 7;
        else if (id.Equals(IAP_minePackageResearchPrice)) return 8;
        else if (id.Equals(IAP_minePackageLv0)) return 9;
        else if (id.Equals(IAP_minePackageLv1)) return 10;
        else if (id.Equals(IAP_minePackageLv2)) return 11;
        else if (id.Equals(IAP_minePackageLv3)) return 12;
        else if (id.Equals(IAP_minePackageLv4)) return 13;
        else if (id.Equals(IAP_HotDeal0)) return 14;
        else if (id.Equals(IAP_HotDeal1)) return 15;
        else if (id.Equals(IAP_HotDeal2)) return 16;
        else if (id.Equals(IAP_HotDeal3)) return 17;
        else if (id.Equals(IAP_HotDeal4)) return 18;
        // else if (id.Equals(IAP_PACK_DungeonVIP)) return 19;
        // else if (id.Equals(IAP_PACK_GemVIP)) return 20;
        // else if (id.Equals(IAP_PACK_MineVIP)) return 21;
        else if (id.Equals(IAP_PACK_MinePass0)) return 22;
        else if (id.Equals(IAP_PACK_MonthlyGem0)) return 23;
        else if (id.Equals(IAP_PACK_MonthlyGem1)) return 24;
        else if (id.Equals(IAP_PACK_StartLv0)) return 25;
        else if (id.Equals(IAP_PACK_StartLv1)) return 26;
        else if (id.Equals(IAP_PACK_StartLv2)) return 27;
        else if (id.Equals(IAP_PACK_StartLv3)) return 28;
        else if (id.Equals(IAP_PACK_DailyLv0)) return 30;
        else if (id.Equals(IAP_PACK_DailyLv1)) return 31;
        else if (id.Equals(IAP_PACK_DailyLv2)) return 32;
        else if (id.Equals(IAP_PACK_DailyLv3)) return 33;
        else if (id.Equals(IAP_PACK_MinePass1)) return 34;
        else if (id.Equals(IAP_PACK_MinePass2)) return 35;
        else if (id.Equals(IAP_PACK_MinePass3)) return 36;
        else if (id.Equals(IAP_PACK_LevelPass0)) return 37;
        else if (id.Equals(IAP_PACK_LevelPass1)) return 38;
        else if (id.Equals(IAP_PACK_LevelPass2)) return 39;
        else if (id.Equals(IAP_PACK_LevelPass3)) return 40;
        else if (id.Equals(IAP_PACK_BookPass)) return 41;
        else if (id.Equals(IAP_PACK_SeasonPass)) return 42;
        else if (id.Equals(IAP_PACK_StagePass0)) return 43;
        else if (id.Equals(IAP_PACK_StagePass1)) return 44;
        else if (id.Equals(IAP_PACK_StagePass2)) return 45;
        else if (id.Equals(IAP_PACK_StagePass3)) return 46;

        return -1;
    }

    public static string Key_SaveData = "Key_SaveData";
    public static string Key_Notification = "Key_Notification";
    public static string KEY_LANGUAGE = "KEY_LANGUAGE";
    public static string Key_ShortChatFormat = "Key_ShortChatFormat{0}";
    public static string Key_BlockUsers = "Key_BlockUsers";
    public static string Key_IsAuto = "Key_IsAuto";
    public static string Key_IsAutoStage = "Key_IsAutoStage";
    public static string NotEnoughCurrency = "not enough currency";
    public static string NotEnoughTicket = "not enough ticket";
    public static string NotEnoughItem = "not enough item";
    public static string Key_PendingPurchaseToken = "Key_PendingPurchaseToken";
    public static string Key_PendingPurchaseProductID = "Key_PendingPurchaseProductID";
    public static string Key_PendingPurchaseOrderID = "Key_PendingPurchaseOrderID";
    public static string Key_PendingPurchaseReward = "Key_PendingPurchaseReward";

    public static string Key_PendingPackageID = "Key_PdngPkgID";
    public static string Key_PendingRewards = "Key_PdngRwrds";
    public static string Key_PetUpgradeScale = "Key_PetUpgradeScale";
    //public static string Key_PetEffectIndex = "Key_PetEffectIndex";
    public static string Key_PetPotionEatRate = "Key_PetPotionEatRate";
    //public static string Key_PetPotionIndexToEat = "Key_PetPotionIndexToEat";
    public static string Key_GuardDragonScore = "Key_GuardDragonScore";
    public static string Key_ScreenSetting = "Key_ScreenSetting";
    public static string Key_BGMVolume = "Key_BGMVolume";
    public static string Key_SFXVolume = "Key_SFXVolume";
    public static string Key_EffectOn = "Key_EffectOn";
    public static string Key_SleepOn = "Key_SleepOn";
    public static string Key_DamageTextOn = "Key_DamageTextOn";
    public static string Key_ShakeOn = "Key_ShakeOn";
    public static string Key_PushOn = "Key_PushOn";
    public static string Key_FrameRate = "Key_FrameRate";
    public static string Key_Playtime = "Key_Playtime";
    public static string Key_MonsterKill = "Key_MonsterKill";
    public static string Key_DeviceKey = "Key_DeviceKey";
    public static string Key_BuffTimeFormat = "Key_BuffTimeFormat{0}";
    public static int ServerCallInterval = 60;
    public static int CountForPromote = 4;
    public static int BuffInterval = 1200;
    public static int FriendLimit = 30;
    public static string Key_LastAccessTime = "Key_LastAccessTime";
    public static string Key_LastCheckTime = "Key_LastCheckTime";
    public static string Key_AutoOnFormat = "Key_AutoOnFormat{0}";
    public static string Key_MaskSkillAutoOn = "Key_MaskSkillAutoOn";
    public static string Key_MaskSkillGauge = "Key_SkillGauge";
    //public static string Key_IdleDiceLeft = "Key_IdleDiceLeft";
    //public static string Key_IdleCoinLeft = "Key_IdleCoinLeft";
    //public static string Key_IdleSpiritLeft = "Key_IdleSpiritLeft";
    //public static string Key_IdleSilverLeft = "Key_IdleSilverLeft";
    //public static string Key_IdleEXPLeft = "Key_IdleEXPLeft";
    //public static string Key_IdleBookLeft = "Key_IdleBookLeft";
    public static string Key_IdleRewardAds = "Key_IdleRewardAds";
    public static string Key_IntroShown = "Key_IntroShown";
    public static string Key_PowerRankScore = "Key_PowerRankScore";
    public static string Key_PowerRankData = "Key_PowerRankData";
    public static string Key_PowerRankTime = "Key_PowerRankTime";
    public static string Key_PVPIORankData = "Key_PVP0RankData";
    public static string Key_PVPIORankTime = "Key_PVP0RankTime";
    public static string Key_PVPIORankScore = "Key_PVP0RankScore";
    public static string Key_PVPAsyncRankData = "Key_PVP1RankData";
    public static string Key_PVPAsyncRankTime = "Key_PVP1RankTime";
    //public static string Key_AutoGachaLevel = "Key_AutoGachaLevel";
    public static string Key_AutoGachaOn = "Key_AutoGachaOn";
    public static string Key_PreviousChannel = "Key_PreviousChannel";
    public static string Key_CurrentCoinEventIndex = "Key_CurrentCoinEventIndex";
    public static string CoinShopPickCount = "CoinShopPickCount";
    public static string CoinBuyFromSuperCoinCount = "CoinBuyFromSuperCoinCount";
    public static string SuperCoinBuyCount = "SuperCoinBuyCount";
    public static string CoinShopLimitPicked0 = "CoinShopLimitPicked0";
    public static string CoinShopLimitPicked1 = "CoinShopLimitPicked1";
    public static string CoinItemPickedFormat = "CoinProductPicked{0}";
    public static string PotionID = "i_0101";
    public static string Key_PVPBestScore = "Key_PVPBestScore";
    public static string Key_Gem = "cr_rdst";
    //public static string Key_DicePerMin = "Key_DicePerMin";
    //public static string Key_EventCoinPerMin = "Key_EventCoinPerMin";
    public static string Key_SilverPerMin = "Key_SilverPerMin";
    public static string Key_ExpPerMin = "Key_ExpPerMin";
    public static string Key_BookPerMin = "Key_BookPerMin";
    public static string DashEffect = "HCFX_Dust_Dash_01_Air";
    public static string CastingEffect = "HCFX_Energy_03";
    public static int TimeTicketMinutes = 5;
    public static string TimeTicketID = "i_0138";
    public static string GodGiftTicketID = "i_0139";
    public static string GachaNTicketID = "i_0140";
    public static string GachaPTicketID = "i_0141";
    public static string CostumeTicketID = "i_0142";
    public static string LCostumeTicketID = "i_0143";
    public static string Key_SpiritStone = "i_0146";
    public static string GoldDungeonTicketID = "i_0103";
    public static string EXPDungeonTicketID = "i_0104";
    public static string WaveDungeonTicketID = "i_0105";
    public static string BossDungeonTicketID = "i_0144";
    public static string IOTicketID = "i_0177";
    public static string SkillTicketID = "i_0145";
    public static string ServerChangeTicketID = "i_0178";
    public static string FriendPointID = "i_0149";
    public static string SlotCore0 = "i_cr_slst1";
    public static string SlotCore1 = "i_cr_slst2";
    public static string Key_FirstPayReceive = "Key_FirstPayRcv";
    public static string Key_FirstPayProgress = "FstPay";

    public static string Key_AutoGachaPerOnce = "Key_AutoGachaPerOnce";
    public static string Key_MajorStatForAuto0 = "Key_MajorStatForAuto0";
    public static string Key_MajorStatForAuto1 = "Key_MajorStatForAuto1";
    public static string Key_SubStatForAuto0 = "Key_SubStatForAuto0";
    public static string Key_SubStatForAuto1 = "Key_SubStatForAuto1";
    public static string Key_AutoGachaRank = "Key_AutoGachaRank";


    public static string Key_WeekyQuest = "Key_WeekyQuest";
    public static string Key_WeekyQuestGet = "Key_WeekyQuestGet";

    public static string Key_LastEquipment = "Key_LastEquipment";
    public static string Key_LastPet = "Key_LastPet";
    public static string Key_LastPower = "Key_LastPower";
    public static string Key_LastLevel = "Key_LastLevel";
    public static string Key_LastCostume = "Key_LastCostume";
    public static string Key_LastMask = "Key_LastMask";
    public static string Key_LastSkills = "Key_LastSkills";
    public static string Key_LastStage = "Key_LastStage";
    public static string Key_AchievementKeyPreFix = "AQ";
    public static string Key_AccountDeleted = "Key_AccountDeleted";
    public static string Key_MineTicketUseCount = "MtUc";
    public static string Key_AutoSell = "Key_AutoSell";
    public static string Key_CameraIndex = "Key_CameraIndex";
    public static string Key_IO_Item = "i_0176";
    public static string Key_IODailyItemCount = "IODItmCnt";
    public static string Key_IOWeeklyItemCount = "IOWItmCnt";
    public static string Key_EquipPassEXP = "EquipPassEXP";
    public static string Key_AdsRewardReceivedDaily = "AdsRwdRcvDaily";
    public static string Key_AdsRewardReceivedWeekly = "AdsRwdRcvWeekly";
    public static string Key_AchievementReceivedKeyPreFix = "AQR";
    public static string Key_FriendRequest = "Key_FriendRequest";
    public static string Key_PvpAsyncMyRank = "Key_PvpAsyncMyRank";
    public static string Key_AutoBoss = "Key_AutoBoss";
    public static string Key_ProfileSaved = "Key_ProfileSaved";
    public static string Key_BattleLog = "Key_BattleLog";
    public static string Key_MIOPVPLog = "Key_MIOPVPLog";
    public static string Key_PVPAsyncLastTime = "Key_PVPAsyncLastTime";
    public static string Key_LastCostumeOption = "Key_LastCostumeOption";
    public static string Key_PVPTicketCount = "PVPTkCnt";
    public static string Key_PVPMatchTime = "PVPTime";
    public static string Key_CostumeEventGachaCount = "CstmeEvtGchCnt";
    public static string Key_LotteryEventGachaCount = "LotryEvtGchCnt";
    public static string Key_CostumeEventRewardReceived = "CostmEvtGchRwdRcv";
    public static string Key_LotteryEventRewardReceived = "LotryEvtGchRwdRcv";
    // public static string Key_PVPRankRefreshRequired = "PVPRankRefresh";
    // public static string Key_DragonRankRefreshRequired = "DragonRankRefresh";
    // public static string Key_IOGameRankRefreshRequired = "IOGameRankRefresh";
    // public static string Key_MineRankRefreshRequired = "MineRankRefresh";
    // public static string Key_PVPRankRefreshTime = "PVPRankRefreshTime";
    // public static string Key_DragonRankRefreshTime = "DragonRankRefreshTime";
    // public static string Key_IOGameRankRefreshTime = "IOGameRankRefreshTime";
    // public static string Key_MineRankRefreshTime = "MineRankRefreshTime";
    public static string Key_DiceLevel = "DcLv";
    public static string Key_DiceEXP = "DcEx";
    public static int DiceSetLength = 61;
    public static int DiceSmallSetLength = 20;
    public static string Key_Indicator = "UI/Indicate/Indicate"; // "Prefab/UI/imgAlert"
    public static int BlockUserMax = 30;
    public static string Key_ServerFilterIndex = "ChatSVFIdx";

    public static string CostumeMaterialKey = "i_0150";
    public static string Key_HideAccessory = "HideAccessory";
    public static string Key_HideEffect = "HideEffect";
    public static string Key_HideMask = "HideMask";
    public static string Key_ChatLanguageOnFormat = "ChatLangOn{0}";
    public static string Key_UpgradeServerFormatOncePreset = "USFO_Preset";

    public static readonly int FreeDungeonTicketCount = 3;
}
